# job --> clones repo into virtual environment and executes phases. fail if script phase non-zero
# phase --> install, script, deploy
# build --> series of jobs
# stage --> series of jobs in parallel

# install --> build --> deploy

# We want fast container based execution
sudo: false
language: c

# Just look at online dashboard
notifications:
  email: false

# Override typical 50 depth clone
git:
  depth: 1

branches:
  except:
    - /^feature\/.*$/
    - /^hotfix\/.*$/
    - /^release\/.*$/

branches:
  only:
    - master
    - develop

matrix:
  fast_finish: true

  include:
	- os: linux
      dist: trusty
	  compiler: gcc-5
	  addons:
	    apt:
		  # Add ppa to allow for unverified libraries
		  sources: 
		    - ubuntu-toolchain-r-test
		  packages:
		    - time
	  script: \
	    autoreconf -i && \
		cd build/ && ../configure && \
		make all && \
		make check
		 
  include:
	- os: linux
      dist: trusty
	  compiler: gcc-6
	  addons:
	    apt:
		  # Add ppa to allow for unverified libraries
		  sources: 
		    - ubuntu-toolchain-r-test
		  packages:
		    - time
	  script: \
	    autoreconf -i && \
		cd build/ && ../configure && \
		make all && \
		make check

  include:
	- os: linux
      dist: trusty
	  compiler: gcc-7
	  addons:
	    apt:
		  # Add ppa to allow for unverified libraries
		  sources: 
		    - ubuntu-toolchain-r-test
		  packages:
		    - time
	  script: \
	    autoreconf -i && \
		cd build/ && ../configure && \
		make all && \
		make check

# before_install, before_script, after_success 
